### ISSUE TITLE
Allow ipytangle to plug and play with interactive

### ISSUE THREAD

**Issue by tonyfast** [bollwyvl/ipytangle#8]
The widgets needs ``value`` to automatically update the backbone model; it also needs a description.  Can ``ipytangle`` be easier to plug into ``interact`` and ``interactive``?

**Comment by bollwyvl** [comment]
Going from interact into tangle is reasonable: once you define an `@interact` function, you get back a function which has a `.widget` member (tuple though, yuck).

Here's [an example](http://nbviewer.ipython.org/gist/bollwyvl/6373c5e81dac80914599).

In the other direction, adding a `value` and `description` is doable, but i guess passing a tangle straight up would mean a pointer to itself so that you still got back the tangle instance... 
```python
t = tangle(x=1)
@interact(t=t)
def foo(t):
    print(t.x + 1)
```

i'd have to figure out how to trigger the change of value on any change on any user-defined traitlet, but that should be okay if it doesn't cause an infinite loop.

As part of #3, i'll end up building widgets to represent all of the traitlets that get created (or reuse ones if a widget value itself is given). that might make this easier, as you could ask for
```python
t = tangle(x=1)
@interact(x=t.widget.x)
def foo(x):
    print(x+1)
```

**Comment by tonyfast** [comment]
That example notebook was super helpful.  Thanks.

Here is a [demo with Bokeh](http://nbviewer.ipython.org/gist/tonyfast/54161463ffb423ce1dbd).  In this demo, I was unable to find a way to pass the trig function to tangle.
